apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-server-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: file-server-ds
  template:
    metadata:
      labels:
        app: file-server-ds
    spec:
      containers:
        - image: harbor.dev-fql.com/middleware/nginx:latest
          imagePullPolicy: Always
          name: file-server-ds
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: vol1
      imagePullSecrets:
        - name: lexin-registry
      volumes:
        - hostPath:
            path: /var/lib/docker/logs/apps/
            type: ""
          name: vol1
