apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-server-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: file-server-ds
  template:
    metadata:
      labels:
        app: file-server-ds
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: file-server-ds
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: log
      volumes:
        - hostPath:
            path: /var/lib/docker/logs/apps/
          name: log
