info:
  contact:
    email: runzhliu@163.com
    name: runzhliu
  description: k8s本地日志服务器
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: container-log-server API
  version: "1.0"
paths:
  /v1/log/download:
    get:
      consumes:
      - application/json
      description: 注意参数格式
      parameters:
      - default: 10.9.70.1
        description: 母机节点
        in: query
        name: host
        required: true
        type: string
      - default: test-a
        description: Pod名
        in: query
        name: pod
        required: true
        type: string
      - default: test
        description: 容器名
        in: query
        name: container
        required: true
        type: string
      - default: test.log
        description: 日志名
        in: query
        name: log
        required: true
        type: string
      responses: {}
      summary: k8s日志下载接口
  /v1/log/list:
    get:
      consumes:
      - application/json
      description: 注意参数格式
      parameters:
      - default: 10.9.70.1
        description: 母机节点
        in: query
        name: host
        required: true
        type: string
      - default: test-a
        description: Pod名
        in: query
        name: pod
        required: true
        type: string
      - default: test
        description: 容器名
        in: query
        name: container
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              properties:
                mtime:
                  type: string
                name:
                  type: string
                size:
                  type: integer
                type:
                  type: string
              type: object
            type: array
      summary: k8s日志清单接口
swagger: "2.0"
